name: SkywarsRemake
version: '${project.version}'
main: net.montal.skywarsremake.SkywarsRemake
api-version: '1.19'
authors: [Zoridon, PillageDev, IncbomDev, Poooooooooolch]
description: A skywars remake by 4 developers
